"""
scrum/backlog/pr_auto_describe.py
When a PR is opened, auto-generate a description from the diff and linked issues.
Fills in the PR template sections: Summary, Linked issues, Testing notes.
Only fills sections that are empty — never overwrites human content.
"""
import argparse
import logging
import re
from scraut.platform.utils.config import load_config
from scraut.platform.github.api import get_github_client, get_sp_from_issue
from scraut.platform.llm.client import complete
from scraut.platform.llm.prompts import SYSTEM_SCRUM_ASSISTANT

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

PR_DESCRIPTION_PROMPT = """
You are writing a GitHub PR description for a developer.

## Linked issues (from PR title/branch):
{issues}

## Files changed:
{files_changed}

## Diff summary:
{diff_summary}

## Instructions:
Write a clear, concise PR description that:
1. Summarises WHAT this PR does (1-2 sentences)
2. Explains WHY (links to the issue goal)
3. Notes what tests were added (if any obvious from diff)
4. Flags anything the reviewer should pay attention to

Keep it under 200 words. Write for a peer reviewer.
Output only the description text — no markdown headers, no preamble.
"""

TEMPLATE_SUMMARY_MARKER = "<!-- What does this PR do? One sentence. -->"
TEMPLATE_NOTES_MARKER = "<!-- Anything the reviewer should pay special attention to -->"


def extract_linked_issues(pr, repo) -> list:
    """Extract issues linked via 'Closes #NNN' in PR title, body, or branch name."""
    text = (pr.title or "") + " " + (pr.body or "") + " " + pr.head.ref
    issue_nums = [int(n) for n in re.findall(r"#(\d+)", text)]
    issues = []
    for num in set(issue_nums):
        try:
            issue = repo.get_issue(num)
            issues.append({
                "number": num,
                "title": issue.title,
                "body": (issue.body or "")[:300],
            })
        except Exception:
            pass
    return issues


def get_diff_summary(pr, max_lines: int = 50) -> str:
    """Get a condensed summary of changed files and key diff lines."""
    files = list(pr.get_files())
    summary_parts = []
    for f in files[:10]:
        summary_parts.append(f"  {f.filename} (+{f.additions}/-{f.deletions})")
    return "\n".join(summary_parts)


def auto_describe_pr(pr_number: int, repo_name: str, config: dict) -> None:
    g = get_github_client()
    repo = g.get_repo(repo_name)
    pr = repo.get_pull(pr_number)

    current_body = pr.body or ""
    if (TEMPLATE_SUMMARY_MARKER not in current_body and
            len(current_body.strip()) > 200):
        logger.info(f"PR #{pr_number} already has description. Skipping.")
        return

    linked_issues = extract_linked_issues(pr, repo)
    if not linked_issues:
        logger.info(f"PR #{pr_number}: no linked issues found. Skipping auto-description.")
        return

    diff_summary = get_diff_summary(pr)
    files_list = "\n".join(f.filename for f in list(pr.get_files())[:15])

    issues_text = "\n".join(
        f"- #{i['number']}: {i['title']}\n  Goal: {i['body'][:150]}"
        for i in linked_issues
    )

    generated_desc = complete(
        PR_DESCRIPTION_PROMPT.format(
            issues=issues_text,
            files_changed=files_list,
            diff_summary=diff_summary,
        ),
        system=SYSTEM_SCRUM_ASSISTANT,
    )

    if not generated_desc:
        return

    closes_section = "\n".join(f"Closes #{i['number']}" for i in linked_issues)

    new_body = f"""## Summary
{generated_desc}

## Linked issues
{closes_section}

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation

## Testing
<!-- How was this tested? -->
- [ ] Unit tests added/updated
- [ ] Tested manually

## Notes for reviewers
<!-- Anything the reviewer should pay special attention to -->
_Auto-generated by Scraut. Please review and edit as needed._
"""

    pr.edit(body=new_body)
    logger.info(f"Auto-described PR #{pr_number}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--pr", type=int, required=True)
    parser.add_argument("--repo", required=True)
    parser.add_argument("--config")
    args = parser.parse_args()
    config = load_config(args.config)
    auto_describe_pr(args.pr, args.repo, config)
