"""
scrum/standup/reset_templates.py
Create standup template files for today for each team member.
CRITICAL: Only creates files that don't exist. Never overwrites existing files.
Bot commits include [skip ci] to avoid triggering standup workflow.
"""
import argparse
import logging
import re
from datetime import date
from pathlib import Path
from scraut.platform.utils.config import load_config, get_workspace_root, get_current_sprint, get_sprint_folder, get_sprint_output_folder, format_sprint_num, get_folder_padding
from scraut.platform.utils.file_utils import create_if_not_exists

YESTERDAY_PLACEHOLDER = re.compile(
    r"(## Yesterday\s*\n)(<!-- What did you complete\? Reference issues/PRs where applicable\. -->)\s*(\n|$)",
    re.IGNORECASE
)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

STANDUP_TEMPLATE = """# Standup — {display_name}
<!--
  Sprint: sprint-{sprint_num}
  Date: {date}
  Author: {login}

  ─── NAVIGATION ──────────────────────────────────────────
  📁 Sprint folder:   sprint-{sprint_num}/
  📋 Sprint meta:     sprint-{sprint_num}/meta.md
  📝 Your standup:    sprint-{sprint_num}/standup/{date}/{login}.md
  💬 Retro (when due): sprint-{sprint_num}/retrospective/{login}.md
  🗒️  Backlog ideas:   sprint-{sprint_num}/grooming/backlog-ideas.md
  🏁 Board:           [GitHub Projects - see scraut.yml portal.project_number]
  ─────────────────────────────────────────────────────────
-->

## Yesterday
<!-- What did you complete? Reference issues/PRs where applicable. -->

## Today
<!-- What will you work on today? Reference issues if possible. -->

## Blockers
<!-- Anything blocking your progress? Scraut tracks these automatically. -->
<!-- Write "None" if no blockers. -->
None

## Notes
<!-- Optional: OOO, reduced availability, context for the team -->
"""

AGENT_STANDUP_TEMPLATE = """# Standup — {display_name}
<!--
  Sprint: sprint-{sprint_num}
  Date: {date}
  Author: {agent_id} (AI agent)
  Auto-generated by: {agent_id} workflow
-->

## Yesterday
<!-- Agent fills this in automatically from commit/PR activity -->

## Today
<!-- Agent fills this in automatically from claimed tasks -->

## Blockers
<!-- Agent fills this in if escalation needed -->
None

## Notes
<!-- Agent state information -->

## Agent State
- Tasks completed this sprint: 0 of 0 assigned
- Velocity: 0 sp delivered
- CI status: unknown
- Last commit: none
- Escalation needed: no
"""


def reset_templates(config: dict, dry_run: bool = False) -> None:
    root = get_workspace_root()
    sprint_num = get_current_sprint()
    today = date.today().isoformat()

    standup_dir = get_sprint_folder(sprint_num) / "standup" / today
    standup_dir.mkdir(parents=True, exist_ok=True)

    summary_dir = get_sprint_output_folder(sprint_num) / "standup" / "summary"
    summary_dir.mkdir(parents=True, exist_ok=True)

    created = []
    for member in config["team"]["members"]:
        login = member["login"]
        display = member["display"]
        file_path = standup_dir / f"{login}.md"

        content = STANDUP_TEMPLATE.format(
            display_name=display,
            sprint_num=format_sprint_num(sprint_num, get_folder_padding()),
            date=today,
            login=login,
        )

        if not dry_run:
            if create_if_not_exists(file_path, content):
                created.append(login)
                logger.info(f"Created standup template for {display}")
            else:
                logger.info(f"Skipped (exists): {display}")
        else:
            logger.info(f"[DRY RUN] Would create: {file_path}")

    if config.get("agents", {}).get("enabled"):
        for agent in config["agents"].get("roles", []):
            if not agent.get("enabled"):
                continue
            agent_id = agent["id"]
            file_path = standup_dir / f"{agent_id}.md"
            content = AGENT_STANDUP_TEMPLATE.format(
                display_name=agent_id,
                sprint_num=format_sprint_num(sprint_num, get_folder_padding()),
                date=today,
                agent_id=agent_id,
            )
            if not dry_run:
                create_if_not_exists(file_path, content)

    logger.info(f"Templates ready for {today}: {len(created)} new, rest already existed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--config")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    config = load_config(args.config)
    reset_templates(config, args.dry_run)
