"""
scripts/sprint/create_planning_pr.py
Create the sprint planning PR: a branch with the proposed sprint backlog.
Team reviews the PR to add/remove issues via review comments.
Merging the PR = team formally commits to the sprint.
This implements the "sprint planning as PR review" ceremony improvement.
"""
import argparse
import logging
from datetime import date
from pathlib import Path
from scripts.utils.config import load_config, get_repo_root, get_current_sprint
from scripts.utils.file_utils import atomic_write, read_file, extract_section
from scripts.github.api import (get_github_client, get_issues, get_sp_from_issue,
                                  ensure_label_exists, add_label_to_issue)
from scripts.llm.client import complete_json
from scripts.llm.prompts import SPRINT_GOAL_SUGGESTION, SYSTEM_SCRUM_ASSISTANT
from scripts.sprint.calculate_velocity import calculate_rolling_velocity

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

PLANNING_PR_CONTENT = """# 🎯 Sprint {sprint_num} — Proposed Backlog

**Suggested sprint goal:** {sprint_goal}

**Capacity:** {capacity} sp/sprint (based on {velocity_sprints}-sprint average)

---

## Proposed sprint issues

| Issue | Title | Type | SP | Priority |
|-------|-------|------|----|---------|
{issue_table}

**Total:** {total_sp} sp

---

## Instructions for team

Review this proposal:
- ✅ Comment `/approve` to accept as-is
- ➕ Comment `/add #NNN` to add an issue
- ➖ Comment `/remove #NNN` to remove an issue
- 📝 Leave review comments on specific lines to discuss individual stories

**Merging this PR = team commits to this sprint scope.**

_Generated by Scraut on {date}_
"""


def get_prioritised_backlog(repo_name: str, config: dict, capacity: int) -> tuple:
    """Get top backlog issues up to capacity SP."""
    g = get_github_client()
    repo = g.get_repo(repo_name)

    all_open = get_issues(repo, state="open")
    backlog = [
        i for i in all_open
        if not any(l.name.startswith("sprint-") or l.name == "in-sprint"
                   for l in i.labels)
    ]

    priority_order = {"p:high": 0, "p:medium": 1, "p:low": 2}

    def issue_priority(issue):
        for label in issue.labels:
            if label.name in priority_order:
                return priority_order[label.name]
        return 3

    backlog.sort(key=issue_priority)

    selected = []
    total_sp = 0
    for issue in backlog:
        sp = get_sp_from_issue(issue)
        if sp == 0:
            sp = 3  # default estimate for unpointed issues
        if total_sp + sp <= capacity:
            selected.append(issue)
            total_sp += sp

    return selected, total_sp


def create_planning_pr(sprint_num: int, repo_name: str, config: dict) -> None:
    g = get_github_client()
    repo = g.get_repo(repo_name)

    velocity = calculate_rolling_velocity(repo_name)
    capacity = round(velocity.get("avg", 26) * config["sprint"].get("capacity_buffer", 0.85))

    selected_issues, total_sp = get_prioritised_backlog(repo_name, config, capacity)

    if not selected_issues:
        logger.warning("No backlog issues found for sprint planning")
        return

    backlog_summary = "\n".join(
        f"- #{i.number}: {i.title} (sp:{get_sp_from_issue(i) or '?'})"
        for i in selected_issues[:10]
    )
    root = get_repo_root()
    prev_meta = ""
    if sprint_num > 1:
        prev_meta = read_file(root / f"sprint-{sprint_num-1:02d}" / "meta.md") or ""
    prev_goal = extract_section(prev_meta, "Goal") if prev_meta else "No previous sprint"

    goal_result = complete_json(
        SPRINT_GOAL_SUGGESTION.format(
            sprint_num=sprint_num,
            backlog_items=backlog_summary,
            velocity=velocity.get("avg", 26),
            prev_goal=prev_goal,
            capacity=capacity,
        ),
        system=SYSTEM_SCRUM_ASSISTANT,
    )
    sprint_goal = goal_result.get("suggested_goal", "Team to define during planning") if goal_result else "Team to define"

    rows = []
    for issue in selected_issues:
        sp = get_sp_from_issue(issue) or "?"
        labels = [l.name for l in issue.labels]
        issue_type = next((l for l in labels if l in ["story", "bug", "task", "spike", "chore"]), "task")
        priority = next((l for l in labels if l.startswith("p:")), "p:medium")
        rows.append(f"| #{issue.number} | {issue.title[:60]} | {issue_type} | {sp} | {priority} |")

    pr_body = PLANNING_PR_CONTENT.format(
        sprint_num=sprint_num,
        sprint_goal=sprint_goal,
        capacity=capacity,
        velocity_sprints=velocity.get("sprints_sampled", 5),
        issue_table="\n".join(rows),
        total_sp=total_sp,
        date=date.today().isoformat(),
    )

    branch_name = f"sprint-{sprint_num:02d}-planning"
    try:
        main_sha = repo.get_branch("main").commit.sha
        repo.create_git_ref(f"refs/heads/{branch_name}", main_sha)
    except Exception as e:
        logger.warning(f"Branch may already exist: {e}")

    planning_path = f"sprint-{sprint_num:02d}/meta.md"
    sprint_meta_content = (
        f"# Sprint {sprint_num:02d}\n"
        f"- Period: TBD\n"
        f"- Goal: {sprint_goal}\n"
        f"- Team: {', '.join(m['display'] for m in config['team']['members'])}\n"
        f"- Committed: {total_sp} story points across {len(selected_issues)} issues\n\n"
        f"## Issues in sprint\n"
        f"| Issue | Title | EP | SP | Assignee |\n"
        f"|-------|-------|-----|-----|----------|\n"
        + "\n".join(
            f"| #{i.number} | {i.title[:50]} | - | {get_sp_from_issue(i) or '?'} | TBD |"
            for i in selected_issues
        )
    )

    try:
        existing = repo.get_contents(planning_path, ref="main")
        repo.update_file(
            planning_path,
            f"chore: sprint {sprint_num} planning proposal [skip ci]",
            sprint_meta_content,
            existing.sha,
            branch=branch_name,
        )
    except Exception:
        repo.create_file(
            planning_path,
            f"chore: sprint {sprint_num} planning proposal [skip ci]",
            sprint_meta_content,
            branch=branch_name,
        )

    pr = repo.create_pull(
        title=f"🎯 Sprint {sprint_num:02d} Planning — {sprint_goal[:60]}",
        body=pr_body,
        head=branch_name,
        base="main",
    )
    pr.add_to_labels("sprint-planning")
    logger.info(f"Created planning PR #{pr.number}: {pr.html_url}")

    sprint_label = f"sprint-{sprint_num:02d}"
    ensure_label_exists(repo, sprint_label, color="0075ca")
    for issue in selected_issues:
        add_label_to_issue(issue, sprint_label)
        add_label_to_issue(issue, "in-sprint")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--sprint", type=int, required=True)
    parser.add_argument("--repo", required=True)
    parser.add_argument("--config")
    args = parser.parse_args()
    config = load_config(args.config)
    create_planning_pr(args.sprint, args.repo, config)
